# Generated by Django 3.0.5 on 2022-07-07 14:04

from django.db import migrations, models
import django.db.models.deletion
import logistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('weight', models.PositiveIntegerField()),
                ('tracking_number', models.CharField(blank=True, default=logistics.models.Shipment.get_tracking_number, max_length=8)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(blank=True, default=False)),
                ('shipment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('source_address', models.TextField()),
                ('destination_adresss', models.TextField()),
                ('sender_name', models.CharField(max_length=40)),
                ('sender_address', models.TextField()),
                ('sender_phone_number', models.CharField(max_length=20)),
                ('sender_email', models.EmailField(max_length=254)),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_destination', to='core.Country')),
                ('source_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_source', to='core.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.Country')),
            ],
        ),
        migrations.CreateModel(
            name='TransitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('arrived', 'arrived'), ('processing', 'processing'), ('dispatched', 'dispatched')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_logs', to='logistics.Shipment')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_logs', to='logistics.Station')),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'registred'), ('received', 'received'), ('processing', 'processing'), ('in transit', 'in transit')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='logistics.Shipment')),
            ],
        ),
    ]
