# Generated by Django 3.0.5 on 2022-07-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='transitlog',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='statuslog',
            old_name='Shipment',
            new_name='shipment',
        ),
        migrations.RenameField(
            model_name='transitlog',
            old_name='event',
            new_name='status',
        ),
    ]
