# Generated by Django 3.0.5 on 2022-07-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20220707_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='destination_adresss',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='source_address',
            field=models.CharField(max_length=200),
        ),
    ]
