# Generated by Django 3.0.5 on 2022-07-07 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_auto_20220707_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 7, 20, 10, 28, 780627, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in dollars($)', max_digits=100),
        ),
    ]
