# Generated by Django 3.0.5 on 2022-07-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_auto_20220707_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='destination_addresss',
            new_name='destination_address',
        ),
    ]
