# Generated by Django 3.0.5 on 2022-07-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_auto_20220707_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=models.CharField(choices=[('registered', 'registered'), ('received', 'received'), ('processing', 'processing'), ('in transit', 'in transit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transitlog',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transitlog',
            name='station',
            field=models.CharField(max_length=30),
        ),
    ]
