# Generated by Django 3.0.5 on 2023-10-01 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_auto_20220710_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='_estimated_arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
