# Generated by Django 3.0.5 on 2023-10-01 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_shipment__estimated_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='_estimated_departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
