# Generated by Django 3.0.5 on 2022-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20220523_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='is_verified',
            new_name='is_accepted',
        ),
        migrations.AddField(
            model_name='kyc',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='driving_license',
            field=models.FileField(blank=True, upload_to='kyc/driving_license/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='first_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='last_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='national_id_back',
            field=models.FileField(blank=True, upload_to='kyc/national_id_back/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='national_id_front',
            field=models.FileField(blank=True, upload_to='kyc/national_id_front/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='nationality',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='passport',
            field=models.FileField(blank=True, upload_to='kyc/passport/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='phone_number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
