# Generated by Django 3.0.5 on 2022-07-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20220625_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_wallet_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_wallet_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_id',
        ),
        migrations.DeleteModel(
            name='KYC',
        ),
        migrations.DeleteModel(
            name='WalletAddress',
        ),
    ]
