# Generated by Django 3.0.5 on 2022-07-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
