# Generated by Django 3.0.5 on 2023-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('img', models.FileField(upload_to='blog')),
            ],
        ),
    ]
