# Generated by Django 3.0.5 on 2022-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='admin',
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
