# Generated by Django 3.0.5 on 2022-03-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20220309_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='approve_investment',
            field=models.BooleanField(default=False),
        ),
    ]
